#!/bin/bash
# This file is managed by Puppet; changes may be overwritten.

to=$1
webhook_url=$2
webhook=$3
service=$4


subject="systemd status change: $service"


## Remove characters that might cause webhook "invalid_payload" error.
status=$(systemctl status "$service" | tr -d '"<>&')


body="
Status of service $service:

$status
"

if [ "$webhook" != "0" ]; then
    header="Content-Type: application/json"

    icon=":red_circle:"
    systemctl -q is-active "$service" && icon=":large_green_circle:"

    subject="$icon *${subject}*"

    ## Post body separately in case it gets rejected for problematic chars.
    for t in "$subject" "$body"; do
        /usr/bin/curl -X POST -H "$header" -d "{ \"text\": \"$t\" }" "$webhook_url"
    done

else

    mail -Ssendwait -s "$subject" "$to" <<EOF
$body
EOF

fi

exit 0
